/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import service.SAVENHANVIEN;

/**
 *
 * @author Asus
 */
public class AMITYC extends javax.swing.JFrame {

    private HoaDon hd;
    private NhanVien nv;
    private ThongKe tk;
    private KhachHang kh;
    private KhuyenMai km;
    private LichSuHoaDon lshd;
    private SanPhamJPanel sp;
    private ThuocTinhJDialog ttsp;
    private boolean tabAdded = false;

    public AMITYC(JPanel PanN_BG, JPanel PanN_ChucNang, JTabbedPane TabPanN_AllChucNang, JLabel jLabel10, JLabel jLabel12, JLabel jLabel14, JLabel jLabel15, JLabel jLabel16, JLabel jLabel2, JLabel jLabel5, JLabel jLabel6, JLabel jLabel8, JLabel lblDangXuat, JLabel lblHoaDon, JLabel lblKhachHang, JLabel lblLichSuHD, JLabel lblNhanVien, JLabel lblSanPham, JLabel lblThongKe, JLabel lblTypeAccount, JLabel tblTile, JTextField txtTypeAccount) throws HeadlessException {
        this.PanN_BG = PanN_BG;
        this.PanN_ChucNang = PanN_ChucNang;
        this.TabPanN_AllChucNang = TabPanN_AllChucNang;
        this.jLabel10 = jLabel10;
        this.jLabel12 = jLabel12;
        this.jLabel14 = jLabel14;
        this.jLabel15 = jLabel15;
        this.jLabel16 = jLabel16;
        this.jLabel2 = jLabel2;
        this.jLabel5 = jLabel5;
        this.jLabel6 = jLabel6;
        this.jLabel8 = jLabel8;
        this.lblDangXuat = lblDangXuat;
        this.lblHoaDon = lblHoaDon;
        this.lblKhachHang = lblKhachHang;
        this.lblLichSuHD = lblLichSuHD;
        this.lblNhanVien = lblNhanVien;
        this.lblSanPham = lblSanPham;
        this.lblThongKe = lblThongKe;
        this.lblTypeAccount = lblTypeAccount;
        this.tblTile = tblTile;
        this.txtTypeAccount = txtTypeAccount;
    }

    public AMITYC() {
        initComponents();
        setLocationRelativeTo(null);
        PanN_BG.setBackground(Color.red);
        txtTypeAccount.setEditable(false);
        txtTenNhanVien.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanN_BG = new javax.swing.JPanel();
        tblTile = new javax.swing.JLabel();
        PanN_ChucNang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblHoaDon = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSanPham = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblLichSuHD = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblKhuyenMai = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TabPanN_AllChucNang = new javax.swing.JTabbedPane();
        lblTypeAccount = new javax.swing.JLabel();
        txtTypeAccount = new javax.swing.JTextField();
        lblTypeAccount1 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblTile.setBackground(new java.awt.Color(0, 0, 0));
        tblTile.setFont(new java.awt.Font("STCaiyun", 1, 48)); // NOI18N
        tblTile.setForeground(new java.awt.Color(255, 255, 255));
        tblTile.setText("4 MEN SHOP");

        PanN_ChucNang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\AMITYC_SHOPV1\\src\\main\\java\\view\\iconpack\\hoadon.png")); // NOI18N

        lblHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoaDon.setText("HÓA ĐƠN");
        lblHoaDon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoaDonMouseClicked(evt);
            }
        });

        lblThongKe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKe.setText("THỐNG KÊ");
        lblThongKe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\AMITYC_SHOPV1\\src\\main\\java\\view\\iconpack\\thongke.png")); // NOI18N

        lblNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhanVien.setText("NHÂN VIÊN");
        lblNhanVien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\AMITYC_SHOPV1\\src\\main\\java\\view\\iconpack\\nhanvien.png")); // NOI18N

        lblKhachHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhachHang.setText("KHÁCH HÀNG");
        lblKhachHang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhachHangMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\AMITYC_SHOPV1\\src\\main\\java\\view\\iconpack\\khachhang.png")); // NOI18N

        lblSanPham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSanPham.setText("SẢN PHẨM");
        lblSanPham.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSanPhamMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\AMITYC_SHOPV1\\src\\main\\java\\view\\iconpack\\sanpham.png")); // NOI18N

        lblLichSuHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLichSuHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLichSuHD.setText("LỊCH SỬ HÓA ĐƠN");
        lblLichSuHD.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblLichSuHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLichSuHDMouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\AMITYC_SHOPV1\\src\\main\\java\\view\\iconpack\\lichsuhd.png")); // NOI18N

        lblDangXuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setText("ĐĂNG XUẤT");
        lblDangXuat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\AMITYC_SHOPV1\\src\\main\\java\\view\\iconpack\\dangxuat.png")); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ĐỔI MẬT KHẨU");
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\AMITYC_SHOPV1\\src\\main\\java\\view\\iconpack\\changepass.png")); // NOI18N

        lblKhuyenMai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhuyenMai.setText("KHUYẾN MẠI");
        lblKhuyenMai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhuyenMaiMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon("D:\\AMITYC_SHOPV2\\src\\main\\java\\view\\iconpack\\khuyenmai.png")); // NOI18N

        javax.swing.GroupLayout PanN_ChucNangLayout = new javax.swing.GroupLayout(PanN_ChucNang);
        PanN_ChucNang.setLayout(PanN_ChucNangLayout);
        PanN_ChucNangLayout.setHorizontalGroup(
            PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanN_ChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanN_ChucNangLayout.createSequentialGroup()
                        .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanN_ChucNangLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PanN_ChucNangLayout.createSequentialGroup()
                                .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(15, 15, 15))
                    .addGroup(PanN_ChucNangLayout.createSequentialGroup()
                        .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanN_ChucNangLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177))
                            .addComponent(lblDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(PanN_ChucNangLayout.createSequentialGroup()
                        .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanN_ChucNangLayout.setVerticalGroup(
            PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanN_ChucNangLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLichSuHD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(PanN_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(8, 8, 8))
        );

        TabPanN_AllChucNang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTypeAccount.setText("LOẠI TÀI KHOẢN  : ");

        txtTypeAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTypeAccount.setForeground(new java.awt.Color(51, 0, 255));

        lblTypeAccount1.setText("TÊN NHÂN VIÊN : ");

        txtTenNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTenNhanVien.setForeground(new java.awt.Color(51, 0, 255));

        javax.swing.GroupLayout PanN_BGLayout = new javax.swing.GroupLayout(PanN_BG);
        PanN_BG.setLayout(PanN_BGLayout);
        PanN_BGLayout.setHorizontalGroup(
            PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanN_BGLayout.createSequentialGroup()
                .addGroup(PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanN_BGLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanN_ChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TabPanN_AllChucNang))
                    .addGroup(PanN_BGLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tblTile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE)
                        .addComponent(lblTypeAccount1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTypeAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTypeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        PanN_BGLayout.setVerticalGroup(
            PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanN_BGLayout.createSequentialGroup()
                .addGroup(PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanN_BGLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(tblTile))
                    .addGroup(PanN_BGLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTypeAccount)
                            .addComponent(txtTypeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTypeAccount1)
                            .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanN_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabPanN_AllChucNang)
                    .addComponent(PanN_ChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanN_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanN_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoaDonMouseClicked
        try {
            setHoaDon();
        } catch (Exception ex) {
            Logger.getLogger(AMITYC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblHoaDonMouseClicked

    private void lblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseClicked
        TabPanN_AllChucNang.removeAll();
        int check = TabPanN_AllChucNang.getComponentCount();
        if (!tabAdded) {
            tk = new ThongKe();
            TabPanN_AllChucNang.addTab("THỐNG KÊ", tk);
            TabPanN_AllChucNang.setSelectedComponent(tk);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabPanN_AllChucNang.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_lblThongKeMouseClicked

    private void lblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseClicked
        TabPanN_AllChucNang.removeAll();
        int check = TabPanN_AllChucNang.getComponentCount();
        if (!tabAdded) {
            nv = new NhanVien();
            TabPanN_AllChucNang.addTab("NHÂN VIÊN", nv);
            TabPanN_AllChucNang.setSelectedComponent(nv);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabPanN_AllChucNang.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_lblNhanVienMouseClicked

    private void lblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseClicked
        TabPanN_AllChucNang.removeAll();
        int check = TabPanN_AllChucNang.getComponentCount();
        if (!tabAdded) {
            try {
                kh = new KhachHang();
            } catch (Exception e) {
                e.printStackTrace();
            }
            TabPanN_AllChucNang.addTab("KHÁCH HÀNG", kh);
            TabPanN_AllChucNang.setSelectedComponent(kh);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabPanN_AllChucNang.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_lblKhachHangMouseClicked

    private void lblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSanPhamMouseClicked
        TabPanN_AllChucNang.removeAll();
        int check = TabPanN_AllChucNang.getComponentCount();
        if (!tabAdded) {
            try {
                sp = new SanPhamJPanel();
//                ttsp = new ThuocTinhJDialog();
            } catch (Exception e) {
                e.printStackTrace();
            }
            TabPanN_AllChucNang.addTab("SẢN PHẨM ", sp);
            TabPanN_AllChucNang.add("THUỘC TÍNH SẢN PHẨM ", ttsp);
            TabPanN_AllChucNang.setSelectedComponent(ttsp);
            TabPanN_AllChucNang.setSelectedComponent(sp);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabPanN_AllChucNang.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_lblSanPhamMouseClicked

    private void lblLichSuHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLichSuHDMouseClicked
        TabPanN_AllChucNang.removeAll();
        int check = TabPanN_AllChucNang.getComponentCount();
        if (!tabAdded) {
            try {
                lshd = new LichSuHoaDon();
            } catch (Exception e) {
                e.printStackTrace();
            }
            TabPanN_AllChucNang.addTab("LỊCH SỬ HÓA ĐƠN", lshd);
            TabPanN_AllChucNang.setSelectedComponent(lshd);
            tabAdded = true;
            // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabPanN_AllChucNang.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_lblLichSuHDMouseClicked

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        int chon = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn đăng xuất ? ", "Thông báo ", JOptionPane.YES_NO_OPTION);
        if (chon != JOptionPane.YES_OPTION) {
            return;
        } else {
            JOptionPane.showMessageDialog(this, "ĐĂNG XUẤT THÀNH CÔNG !");
            dispose();
            DangNhap dn = new DangNhap(this, true);
            dn.setVisible(true);
        }
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DangNhap dn = new DangNhap(this, true);
        dn.setVisible(true);
        LoginsuccesFully();
    }//GEN-LAST:event_formWindowOpened

    private void LoginsuccesFully() {
        try {
            txtTenNhanVien.setText(SAVENHANVIEN.luuNguoiDung.getHoTen());
            if (SAVENHANVIEN.luuNguoiDung.getVaiTro() == 0) {
                txtTypeAccount.setText("NHÂN VIÊN");
                lblNhanVien.setEnabled(false);
//                lblNhanVienMouseClicked(evt);
                setHoaDon();
            } else if (SAVENHANVIEN.luuNguoiDung.getVaiTro() == 1) {
                txtTypeAccount.setText("QUẢN LÍ");
                lblNhanVien.setEnabled(true);
                setHoaDon();
            }

        } catch (Exception e) {
            System.out.println("Lỗi  " + e);

        }

    }

    public void setHoaDon() throws Exception {
        TabPanN_AllChucNang.removeAll();
        int check = TabPanN_AllChucNang.getComponentCount();
        if (!tabAdded) {
            hd = new HoaDon();
            TabPanN_AllChucNang.addTab("HÓA ĐƠN", hd);
            TabPanN_AllChucNang.setSelectedComponent(hd);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabPanN_AllChucNang.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }
    private void lblKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhuyenMaiMouseClicked
        TabPanN_AllChucNang.removeAll();
        int check = TabPanN_AllChucNang.getComponentCount();
        if (!tabAdded) {
            km = new KhuyenMai();
            TabPanN_AllChucNang.addTab("KHUYẾN MẠI", km);
            TabPanN_AllChucNang.setSelectedComponent(km);
            tabAdded = true; // Đánh dấu đã thêm tab
        } else {
            // Nếu đã thêm tab và số lượng tab trở lại 0, reset lại biến tabAdded
            if (TabPanN_AllChucNang.getTabCount() == check) {
                tabAdded = false;
            }
        }
    }//GEN-LAST:event_lblKhuyenMaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AMITYC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AMITYC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AMITYC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AMITYC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AMITYC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanN_BG;
    private javax.swing.JPanel PanN_ChucNang;
    private javax.swing.JTabbedPane TabPanN_AllChucNang;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblKhuyenMai;
    private javax.swing.JLabel lblLichSuHD;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblSanPham;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblTypeAccount;
    private javax.swing.JLabel lblTypeAccount1;
    private javax.swing.JLabel tblTile;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTypeAccount;
    // End of variables declaration//GEN-END:variables
}
